refactor(fuzz): add `#[cfg(fuzzing)]`
`quinn-proto` exposes some hooks for fuzzing only. These are behind a `#[cfg(fuzzing)]`.

The `fuzz` crate imports these hooks, but without the `#[cfg(fuzzing)]`.

Running `cargo check --workspace` thus fails importing each of these hooks. For example:

```
error[E0432]: unresolved import `proto::fuzzing`
  --> fuzz/fuzz_targets/packet.rs:7:5
   |
7  |     fuzzing::{PacketParams, PartialDecode},
   |     ^^^^^^^ could not find `fuzzing` in `proto`
```

This commit adds the various `#[cfg(fuzzing)]` to `fuzz/`, preventing the above errors.