Increase type_length_limit to 2121396
Previously rustc would fail with
error: reached the type-length limit while instantiating
`<std::vec::IntoIter<Peer> as std...rs:216:58: 220:6 keylog:&bool]]>`

(cherry picked from commit 817a57d281d5958c968fa9ce652b42bddae8f3f4)